version: "3.7"

services:

  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    volumes:
      - ./mysql/vol_data:/var/lib/mysql
      - ./mysql/sql_conf:/etc/mysql/conf.d
      - ./mysql/sql_init:/docker-entrypoint-initdb.d
      - ./mysql/sql_data:/data
    networks:
      - backnet

  app:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      MYSQL_HOST: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '5000'
    depends_on:
      - db
    networks:
      - backnet
      - frontnet

  proxy:
    build: ./nginx
    container_name: nginx_flask
    restart: always
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - frontnet

networks:
  backnet:
  frontnet:
